package gamestructure.ingamemenu.utilities;

public enum Images {
    BACKGROUNDMENU, BACKGROUNDSHOP, BTNRESUME, BTNEXIT, BTNSHOP, BTNRETURNMENU, BTNARTHEMIDEBOW, BTNHEALTH, BTNHERMESBOOTS, BTNZEUSBOLT, BTNORACLEAMULET
}
